FROM openjdk:8 as mysqldoc
EXPOSE 8768
WORKDIR /CustomerProducer

# Copy maven executable to the image
COPY mvnw .
COPY .mvn .mvn

# Copy the pom.xml file
COPY pom.xml .

# Copy the project source
COPY ./src ./src
COPY ./pom.xml ./pom.xml

RUN chmod 755 /CustomerProducer/mvnw

RUN ./mvnw dependency:go-offline -B

RUN ./mvnw package -DskipTests
RUN ls -al
ENTRYPOINT ["java","-jar","CustomerProducer-0.0.1-SNAPSHOT.jar"]